version: '3'
services:
  chessterix_front:
    container_name: chessterix
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/chessterix_front
    ports:
      - '3000:3000'
    tty: true
