const actionTypes = {
  NEW_MOVE: 'NEW_MOVE',
  GENERATE_CANDIDATE_MOVES: 'GENERATE_CANDIDATE_MOVES',
  CLEAR_CANDIDATE_MOVES: 'CLEAR_CANDIDATE_MOVES',
  PROMOTION_OPEN: 'PROMOTION_OPEN',
  PROMOTION_CLOSE: 'PROMOTION_CLOSE',
  CAN_CASTLE: 'CAN_CASTLE',
  STALEMATE: 'STALEMATE',
  INSUFFICIENT_MATERIAL: 'INSUFFICIENT_MATERIAL',
  THREEFOLD_REPETITION: 'THREEFOLD_REPETITION',
  FIFTY_MOVE_RULE: 'FIFTY_MOVE_RULE',
  WIN: 'WIN',
  NEW_GAME: 'NEW_GAME',
  TAKE_BACK: 'TAKE_BACK',
  GO_FORWARD: 'GO_FORWARD',
};

export default actionTypes;
